apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: rmohr/activemq:5.15.9-alpine
          env:
            - name: ACTIVEMQ_OPTS
              value: '-Xms2G -Xmx60G'
          volumeMounts:
            - name: {{ .Release.Name }}-conf
              mountPath: /opt/apache-activemq-5.15.9/conf/activemq.xml
              subPath: activemq.xml
      volumes:
        - name: {{ .Release.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-conf
            defaultMode: 420
